apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-test-config
data:
  application-k8s.yml: |
    server:
      port: 8080

    spring:
      application:
        name: docker-test-service

    app:
      message: "Hello from Kubernetes ConfigMap"
