apiVersion: v1
kind: Service
metadata:
  name: docker-test-service
spec:
  type: NodePort
  selector:
    app: docker-test-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
      protocol: TCP
